from .medicoSerializer import MedicoSerializer
from .usuarioSerializer import UsuarioSerializer
from .enfermeroSerializer import EnfermeroSerializer
from .enfermeropacienteSerializer import EnfermeroPacienteSerializer
from .historiaSerializer import HistoriaSerializer
from .pacienteSerializer import PacienteSerializer
from .familiarSerializer import FamiliarSerializer
