# Generated by Django 4.1.1 on 2022-10-03 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalBackend', '0002_remove_paciente_enfermero_remove_paciente_familiar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='enfermero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalBackend.enfermero'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='familiar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalBackend.familiar'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalBackend.historia'),
        ),
    ]
